package image

import (
	"GoNexus/config"
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"mime/multipart"
	"net/http"
	"path/filepath"
	"strings"
)

// OpenAICompatibleVisionRequest 定义视觉大模型请求体结构
type OpenAICompatibleVisionRequest struct {
	Model    string    `json:"model"`
	Messages []Message `json:"messages"`
}

type Message struct {
	Role    string    `json:"role"`
	Content []Content `json:"content"`
}

type Content struct {
	Type     string    `json:"type"`
	Text     string    `json:"text,omitempty"`
	ImageURL *ImageURL `json:"image_url,omitempty"`
}

type ImageURL struct {
	URL string `json:"url"`
}

// 响应结构体
type AIResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error"`
}

// RecognizeImage 后端图像内容分析逻辑（使用多模态大模型）
func RecognizeImage(file *multipart.FileHeader) (string, error) {
	log.Printf("[Backend] Starting AI Vision analysis for: %s", file.Filename)

	// 1. 读取图片文件并转换为 Base64
	src, err := file.Open()
	if err != nil {
		return "", fmt.Errorf("failed to open image: %v", err)
	}
	defer src.Close()

	imgData, err := io.ReadAll(src)
	if err != nil {
		return "", fmt.Errorf("failed to read image data: %v", err)
	}

	ext := strings.ToLower(filepath.Ext(file.Filename))
	mimeType := "image/jpeg"
	if ext == ".png" {
		mimeType = "image/png"
	} else if ext == ".webp" {
		mimeType = "image/webp"
	}

	base64Str := base64.StdEncoding.EncodeToString(imgData)
	dataURL := fmt.Sprintf("data:%s;base64,%s", mimeType, base64Str)

	// 2. 获取配置
	conf := config.GetConfig()
	apiKey := conf.RagModelConfig.RagApiKey
	baseURL := conf.RagModelConfig.RagBaseUrl
	if apiKey == "" || baseURL == "" {
		return "", fmt.Errorf("AI API Key or Base URL is missing in config")
	}

	// 3. 构建请求 Payload
	reqBody := OpenAICompatibleVisionRequest{
		Model: "qwen-vl-plus", // 默认使用百炼的 vl-plus 模型
		Messages: []Message{
			{
				Role: "user",
				Content: []Content{
					{
						Type: "text",
						Text: "You are the GoNexus Intelligence Engine. Please analyze this image and provide a concise, professional description of the main objects, colors, and key features. Return the result in pure text.",
					},
					{
						Type: "image_url",
						ImageURL: &ImageURL{
							URL: dataURL,
						},
					},
				},
			},
		},
	}

	jsonPayload, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("failed to marshal JSON payload: %v", err)
	}

	// 4. 发送 HTTP 请求
	apiEndpoint := strings.TrimRight(baseURL, "/") + "/chat/completions"
	req, err := http.NewRequest("POST", apiEndpoint, bytes.NewBuffer(jsonPayload))
	if err != nil {
		return "", fmt.Errorf("failed to create HTTP request: %v", err)
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("failed to call AI Vision API: %v", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read API response: %v", err)
	}

	// 5. 解析返回结果
	var aiResp AIResponse
	if err := json.Unmarshal(respBody, &aiResp); err != nil {
		log.Printf("Raw API Response: %s", string(respBody))
		return "", fmt.Errorf("failed to parse AI response JSON: %v", err)
	}

	if aiResp.Error != nil {
		return "", fmt.Errorf("AI API Error: %s", aiResp.Error.Message)
	}

	if len(aiResp.Choices) > 0 {
		return aiResp.Choices[0].Message.Content, nil
	}

	return "No result generated by AI Vision model.", nil
}
