[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "ywto nwxo npjd qgul"
email = "1129271075awm@gmail.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

 [rabbitmqConfig]
  host= "127.0.0.1"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"

  [ragModelConfig]
   embeddingModel= "text-embedding-v4"
   chatModelName="qwen-coder-turbo-0919"
   docDir = "./docs"
   baseUrl="https://dashscope.aliyuncs.com/compatible-mode/v1"
   dimension=1024
   apiKey = "sk-ea57ba41a87e4419b1c7f47e518e6510"

  [voiceServiceConfig]
  voiceServiceApiKey = "sFmibAerX8hj4cV65UPJBtFj"
  voiceServiceSecretKey ="zOIoVoUnVsLuPqdTxzuX2omUyU5Pgc7k"
